version: '3.7'

services:

  app:
    container_name: nestjs-app
    restart: always
    build:
      context: ./docker
      dockerfile: Dockerfile.dev
    command: npm run start
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./src/app:/app
    links:
      - rabbitmq
      - redis
    depends_on:
      - rabbitmq
      - redis

  event-service-rabbit:
    container_name: nestjs-event-service-rabbit
    restart: always
    build:
      context: ./docker
      dockerfile: Dockerfile.dev
    command: npm run start
    tty: true
    volumes:
      - ./src/event-service-rabbit:/app
    links:
      - rabbitmq
    depends_on:
      - rabbitmq

  event-service-redis:
    container_name: nestjs-event-service-redis
    restart: always
    build:
      context: ./docker
      dockerfile: Dockerfile.dev
    command: npm run start
    tty: true
    volumes:
      - ./src/event-service-redis:/app
    links:
      - redis
    depends_on:
      - redis

  redis:
    image: redis:latest
    restart: always
    command: redis-server --requirepass password123
    environment:
      - REDIS_PASSWORD=password123

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - ./docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins